run:
  timeout: 5m
  tests: true

linters-settings:
  misspell:
    ignore-words:
      - Greif # Jonas Greif (Porsche Supercup driver surname)

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - gosec
    - misspell
    - errcheck
    - revive

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

