// Russian localization data (mapping tables, reasons, etc.)
// Logic that uses these mappings stays in app.js; this file only provides data.
(function () {
  if (typeof window === 'undefined') return;

  window.TGA_RU = window.TGA_RU || {};

  // Race statistics keys (lowercase -> ru)
  window.TGA_RU.raceStatKeysRu = {
    'cautions/laps':          'Машины безопасности / Круги',
    'cautions / laps':        'Машины безопасности / Круги',
    'cautions':               'Машины безопасности',
    'red flags':              'Красные флаги',
    'time of race':           'Время гонки',
    'average speed':          'Средняя скорость',
    'margin of victory':      'Отрыв победителя',
    'lap leaders':            'Лидеры по кругам',
    'lead changes':           'Смены лидера',
    'pole winner':            'Поулситтер',
    'pole speed':             'Скорость поула',
    'race distance':          'Дистанция гонки',
    'laps':                   'Кругов',
    'distance':               'Дистанция',
    'winners avg. speed':     'Средняя скорость победителя',
    'winning speed':          'Скорость победителя',
    'winning margin':         'Отрыв победителя',
    'total laps':             'Всего кругов',
    'laps under caution':     'Круги под SC',
    'laps led':               'Круги в лидерах',
    'cars running at finish': 'Финишировали',
    'weather':                'Погода',
    'race winner':            'Победитель',
    'fastest lap':            'Быстрейший круг',
    'fastest lap speed':      'Скорость быстрейшего круга',
    'total cars':             'Всего автомобилей',
    'dnf':                    'Сходы'
  };

  // Spec keys (lowercase -> ru)
  window.TGA_RU.specKeyRu = {
    'generation':                         'Поколение',
    'chassis':                            'Шасси',
    'model':                              'Модель',
    'body type':                          'Тип кузова',
    'body structure':                     'Конструкция кузова',
    'length':                             'Длина',
    'overall length':                     'Общая длина',
    'width':                              'Ширина',
    'overall width':                      'Общая ширина',
    'height':                             'Высота',
    'overall height':                     'Общая высота',
    'wheelbase':                          'Колёсная база',
    'minimum weight':                     'Минимальный вес',
    'minimum weight (no driver / fuel)':  'Минимальный вес (без водителя / топлива)',
    'minimum weight (with driver + fuel)':'Минимальный вес (с водителем и топливом)',
    'minimum weight (with driver)':       'Минимальный вес (с водителем)',
    'engine':                             'Двигатель',
    'engine configuration':               'Конфигурация двигателя',
    'engine displacement':                'Рабочий объём двигателя',
    'induction':                          'Впуск',
    'induction & aspiration':             'Впуск и наддув',
    'aspiration':                         'Наддув',
    'carburetor flow limit':              'Ограничение потока карбюратора',
    'power output':                       'Мощность',
    'power output restriction':           'Ограничение мощности',
    'horsepower':                         'Мощность',
    'torque':                             'Крутящий момент',
    'drivetrain':                         'Привод',
    'transmission':                       'Трансмиссия',
    'suspension':                         'Подвеска',
    'suspension (front)':                 'Передняя подвеска',
    'front suspension':                   'Передняя подвеска',
    'suspension (rear)':                  'Задняя подвеска',
    'rear suspension':                    'Задняя подвеска',
    'brakes':                             'Тормоза',
    'wheels':                             'Колёсные диски',
    'tires':                              'Шины',
    'fuel':                               'Топливо',
    'fuel type':                          'Тип топлива',
    'fuel system':                        'Топливная система',
    'fuel capacity':                      'Объём топливного бака',
    'aerodynamics':                       'Аэродинамика',
    'underbody':                          'Днище',
    'safety':                             'Безопасность',
    'safety equipment':                   'Оборудование безопасности',
    'key features':                       'Ключевые особенности',
    'vehicle type':                       'Тип транспортного средства',
    'manufacturer involvement':           'Участие производителя',
    'approved chassis builders':          'Одобренные производители шасси',
    'weight':                             'Вес',
    'displacement':                       'Объём двигателя',
    'top speed':                          'Максимальная скорость',
    'acceleration':                       'Разгон',
    'gearbox':                            'Коробка передач',
    'tire supplier':                      'Поставщик шин',
    'front wing':                         'Переднее антикрыло',
    'rear wing':                          'Заднее антикрыло',
    'monocoque':                          'Монокок',
    'competition principle':              'Принцип соревнований',
    'drive layout':                       'Компоновка привода',
    'body shell':                         'Кузов',
    'body materials':                     'Материалы кузова',
    'downforce level':                    'Уровень прижимной силы',
    'minimum front axle load':            'Мин. нагрузка на переднюю ось',
    'fuel tank capacity':                 'Объём топливного бака',
    'differential':                       'Дифференциал',
    'clutch':                             'Сцепление',
    'dampers':                            'Амортизаторы',
    'brakes (front)':                     'Тормоза (перед)',
    'brakes (rear)':                      'Тормоза (зад)',
    'tyres':                              'Шины',
    'tire supplier':                      'Поставщик шин',
    'tire construction':                  'Конструкция шин',
    'ecu':                                'ЭБУ',
    'engine allocation':                  'Лимит двигателей',
    'engines per season':                 'Двигателей за сезон',
    'top speed (historical max)':         'Макс. скорость (рекорд)',
    'expected 2026 top speed':            'Ожидаемая макс. скорость 2026',
    'relative performance':               'Относительная производительность',
    'target build cost (no engine)':      'Целевая стоимость сборки (без двигателя)',
    'estimated season cost':              'Оценка стоимости сезона',
    'generation / chassis':               'Поколение / шасси',
    'power output':                       'Мощность',
    'power-to-weight':                    'Мощность/масса',
    'steering':                           'Рулевое управление',
    'steering wheel':                     'Руль',
    'size':                               'Размеры',
    'teams':                              'Команды',
    'series':                             'Серия',
    'season':                             'Сезон',
    'races':                              'Гонки',
    'track compatibility':                'Совместимость с трассами',
    'removed components (2018 redesign)': 'Удалённые компоненты (редизайн 2018)',
    'cockpit modifications':              'Изменения кокпита',
    'cockpit protection (2019)':          'Защита кокпита (2019)',
    'aeroscreen (2020–present)':          'Aeroscreen (2020–н.в.)',
    'engine (2018–2023)':                 'Двигатель (2018–2023)',
    'hybrid powertrain (2024–present)':   'Гибридная силовая установка (2024–н.в.)',
    'current chassis status':             'Статус шасси',
    'tire types – road/street':           'Типы шин — шоссе/город',
    'tire types – ovals':                 'Типы шин — овалы',
    'rain tires':                         'Дождевые шины',
    'display system':                     'Система отображения',
    'design inspiration':                 'Дизайн-вдохновение',
    'aero kit introduction':              'Введение аэрокита',
    'aerodynamic concept':                'Аэродинамическая концепция',
    'downforce change':                    'Изменение прижимной силы',
    'co2 reduction':                      'Снижение CO₂',
    'power limiting':                     'Ограничение мощности',
    'configuration':                      'Конфигурация',
    'body construction':                  'Конструкция кузова',
    'calipers / brake discs':             'Суппорты / тормозные диски',
    'brake pads':                         'Тормозные колодки',
    'lubricants':                         'Смазочные материалы',
    'power':                              'Мощность'
  };

  // Table headers (lowercase -> ru)
  window.TGA_RU.tableHeaderRu = {
    'pos':                    'Поз.',
    'car':                    '#',
    'car #':                  'Ном.',
    '#':                      '#',
    'no.':                    '#',
    'no':                     '#',
    'driver':                 'Пилот',
    'constructor':            'Конструктор',
    'official team':          'Команда',
    'team':                   'Команда',
    'manufacturer':           'Произв.',
    'best time':              'Лучш. время',
    'speed':                  'Скорость',
    'lap #':                  'Круг',
    'lap':                    'Круг',
    'laps':                   'Кругов',
    '# laps':                 'Кругов',
    'gap to leader':          'Отставание',
    'gap to next':            'До след.',
    'gap':                    'Отставание',
    'diff':                   'Разница',
    'grid':                   'Старт',
    'status':                 'Статус',
    'pts':                    'Очки',
    'points':                 'Очки',
    'bonus pts':              'Бонус',
    'laps led':               'Лидировал',
    'led':                    'Лид.',
    'time/retired':           'Время/сход',
    'best lap':               'Лучший круг',
    'points':                 'Очки',
    'pos.':                   'Поз.',
    'fin / st':               'Фин./ст.',
    'st':                     'Ст.',
    'start pos':              'Старт. поз.',
    'starting pos':           'Старт. поз.',
    'starting position':      'Старт. поз.',
    'finishing pos':          'Фин. поз.',
    'finishing position':     'Фин. поз.',
    'flag':                   'Флаг',
    'reason':                 'Причина',
    'leader':                 'Лидер',
    'laps of caution':        'Кругов SC',
    'caution':                'SC',
    'total pts':              'Всего очков',
    'stage pts':              'Очки стейдж',
    'chassis':                'Шасси',
    'crew chief':             'Крю чиф',
    'condition':              'Состояние',
    'from lap':               'С круга',
    'to lap':                 'По круг',
    '# of laps':              'Кругов',
    'free pass':              'Своб. проезд',
    'type':                   'Тип',
    'parameter':              'Параметр',
    'class':                  'Класс',
    'value':                  'Значение',
    'gtd pro':                'GTD Pro',
    'gtd':                    'GTD',
    'make':                   'Марка',
    'tire':                   'Шины',
    'tyre':                   'Шины',
    'driver 1':               'Пилот 1',
    'driver 2':               'Пилот 2',
    'driver 3':               'Пилот 3',
    'lmdh regulation requirement': 'Требование регламента LMDh',
    'lmh regulation':         'Регламент LMH',
    'lmp2 regulation (2028)': 'Регламент LMP2 (2028)',
    'gtd / gtd pro':          'GTD / GTD Pro',
    'incident':               'Инцидент',
    'cars involved':          'Авт.',
    'fastest lap':            'Лучший круг',
    'car no':                 '№',
    'st pos':                 'Старт',
    'no laps':                'Кругов',
    'class pos':              'Поз. в классе',
    'grand prix':             'Гран-при',
    'length':                 'Длина',
    'classes':                'Классы',
    'race date':              'Дата гонки',
    'venue':                  'Трасса',
    'rd.':                    'Эт.',
    'rd':                     'Эт.',
    'drivers':                'Пилоты',
    'time of the day':        'Время суток'
  };

  // Cell notes (exact match, lowercase)
  window.TGA_RU.cellNotesRu = {
    'disallowed after post-race inspection':      'Снят после технической проверки',
    'disallowed after post race inspection':       'Снят после технической проверки',
    'failed post-race inspection':                 'Не прошёл технический осмотр',
    'failed post race inspection':                 'Не прошёл технический осмотр',
    'disqualified':                                'Дисквалифицирован',
    'disqualified after post-race inspection':     'Дисквалифицирован после проверки',
    'did not start':                               'Не стартовал',
    'did not qualify':                             'Не прошёл квалификацию',
    'did not attempt':                             'Не принял участие',
    'withdrew':                                    'Снялся',
    'withdrawn':                                   'Снят',
    'accident':                                    'Авария',
    'engine failure':                              'Отказ двигателя',
    'transmission failure':                        'Отказ трансмиссии',
    'electrical failure':                          'Электрическая неисправность',
    'suspension failure':                          'Отказ подвески',
    'brake failure':                               'Отказ тормозов',
    'tire failure':                                'Прокол шины',
    'crash':                                       'Авария',
    'contact':                                     'Контакт',
    'overheating':                                 'Перегрев',
    'power steering failure':                      'Отказ ГУР',
    'fuel pressure':                               'Проблемы с топливом',
    'oil leak':                                    'Утечка масла',
    'lapped':                                      'На круг позади',
    'running':                                     'Финишировал',
    'dnf':                                         'Сход',
    'dns':                                         'Не стартовал',
    'dnq':                                         'DNQ',
    'wth':                                         'Снялся'
  };

  // Caution / SC reason patterns (most specific first)
  window.TGA_RU.raceReasonExact = {
    'conditions': 'Условия',
    'competition': 'Период SC',
    'medical': 'Медицинская',
    'rain': 'Дождь',
    'tire': 'Шина',
    'debris': 'Обломки',
    'accident': 'Авария',
    'none': '—'
  };
  window.TGA_RU.raceReasonParts = [
    // IndyCar-style prefixes
    [/^Contact;\s*/i, 'Контакт: '],
    [/^Contact:\s*Cars?\s+(.+?)\s+in\s+Turn\s+(\d+)/i, 'Контакт: автомобили $1 в повороте $2'],
    [/^Contact:\s*Car\s+(\d+)\s+in\s+Turn\s+(\d+)/i, 'Контакт: автомобиль $1 в повороте $2'],
    [/^Spin:\s*Car\s+(\d+)\s+in\s+Turn\s+(\d+)/i, 'Разворот: автомобиль $1 в повороте $2'],
    [/^Spin:\s*Car\s+(\d+)\s+on\s+Backstretch/i, 'Разворот: автомобиль $1 на задней прямой'],
    [/^Spin:\s*Car\s+(\d+)\s+on\s+Front Straight/i, 'Разворот: автомобиль $1 на финишной прямой'],
    [/^Debris:\s*Turn\s+(\d+)/i, 'Обломки: поворот $1'],
    [/^Loose Tire:\s*Car\s+(\d+)\s+in\s+Turn\s+(\d+)/i, 'Отсоединившееся колесо: автомобиль $1 в повороте $2'],
    [/^Mechanical:\s*Car\s+(\d+)\s+in\s+Turn\s+(\d+)/i, 'Техническая неисправность: автомобиль $1 в повороте $2'],
    [/^Mechanical:\s*Car\s+(\d+)\s+on\s+Front Straight/i, 'Техническая неисправность: автомобиль $1 на финишной прямой'],
    [/^Mechanical:\s*Car\s+(\d+)$/i, 'Техническая неисправность: автомобиль $1'],
    [/\s*\/\s*Conditions$/i, ''],
    // Scheduled / stage
    [/\bscheduled competition caution\b/gi, 'плановый период SC'],
    [/\bscheduled caution\b/gi, 'плановый период SC'],
    [/\bscheduled break\b/gi, 'плановый перерыв'],
    [/\bend of stage (\d+)/gi, 'конец стейджа $1'],
    [/\bstage (\d+) conclusion\b/gi, 'окончание стейджа $1'],
    [/\baccident (\d+) \/ stage (\d+) conclusion\b/gi, 'авария $1 / окончание стейджа $2'],
    [/\baccident (\d+) no\.?\s*([\d\s&]+)/gi, 'авария $1, авт. $2'],
    // Stopped / stalled / slow
    [/#([\d,]+)\s+stopped on track\b/gi, '#$1 остановился на трассе'],
    [/#([\d,]+)\s+stopped backstretch\b/gi, '#$1 остановился на задней прямой'],
    [/#([\d,]+)\s+stopped turn (\d+)/gi, '#$1 остановился в повороте $2'],
    [/\bstopped turn (\d+)/gi, 'остановка в повороте $1'],
    [/#([\d,]+)\s+stalled on track\b/gi, '#$1 заглох на трассе'],
    [/#([\d,]+)\s+stalled turn (\d+)/gi, '#$1 заглох в повороте $2'],
    [/\bstalled turn (\d+)/gi, 'заглох в повороте $1'],
    [/#([\d,]+)\s+slow on track\b/gi, '#$1 медленно на трассе'],
    [/\bslow on track\b/gi, 'медленно на трассе'],
    // Spin
    [/#([\d,]+)\s+spun turn (\d+)\s*\/\s*stage (\d+) conclusion/gi, '#$1 разворот в повороте $2 / окончание стейджа $3'],
    [/#([\d,]+)\s+spun turn (\d+)/gi, '#$1 разворот в повороте $2'],
    [/\bspun turn (\d+)\s*\/\s*stage (\d+) conclusion/gi, 'разворот в повороте $1 / окончание стейджа $2'],
    [/\bspun turn (\d+)/gi, 'разворот в повороте $1'],
    [/#([\d,]+)\s+spun backstretch\b/gi, '#$1 разворот на задней прямой'],
    [/#([\d,]+)\s+spun frontstretch\b/gi, '#$1 разворот на финишной прямой'],
    [/#([\d,]+)\s+spun (\d+)\s*\/\s*stage (\d+)/gi, '#$1 разворот $2 / стейдж $3'],
    [/#([\d,]+)\s+spun\b/gi, '#$1 разворот'],
    [/\bspun on backstretch\b/gi, 'разворот на задней прямой'],
    [/\bspun backstretch\b/gi, 'разворот на задней прямой'],
    [/\bspun frontstretch\b/gi, 'разворот на финишной прямой'],
    // Multi-car accidents with car numbers
    [/#([\d,]+)\s+accident turn (\d+)/gi, '#$1 авария в повороте $2'],
    [/#([\d,]+)\s+accident backstretch\b/gi, '#$1 авария на задней прямой'],
    [/#([\d,]+)\s+accident frontstretch\b/gi, '#$1 авария на финишной прямой'],
    [/#([\d,]+)\s+accident tri-oval\b/gi, '#$1 авария на три-овале'],
    [/#([\d,]+)\s+accident (\d+)/gi, '#$1 авария $2'],
    [/#([\d,]+)\s+accident\b/gi, '#$1 авария'],
    [/#([\d,]+)\s+engine\b/gi, '#$1 отказ двигателя'],
    // Generic accidents / debris
    [/\baccident frontstretch\b/gi, 'авария на финишной прямой'],
    [/\baccident backstretch\b/gi, 'авария на задней прямой'],
    [/\baccident tri-oval\b/gi, 'авария на три-овале'],
    [/\baccident turn (\d+)/gi, 'авария в повороте $1'],
    [/\baccident\b/gi, 'авария'],
    [/\bdebris turn (\d+)/gi, 'обломки в повороте $1'],
    [/\bdebris backstretch\b/gi, 'обломки на задней прямой'],
    [/\bdebris frontstretch\b/gi, 'обломки на финишной прямой'],
    [/\bdebris\b/gi, 'обломки'],
    [/\bfluid on track\b/gi, 'жидкость на трассе'],
    [/\boil on track\b/gi, 'масло на трассе'],
    [/\bfuel on track\b/gi, 'топливо на трассе'],
    [/\bfire\b/gi, 'пожар'],
    [/\bstalled car\b/gi, 'заглохший автомобиль'],
    [/\bwreck\b/gi, 'авария'],
    [/\bfronstretch\b/gi, 'финишная прямая'],
    [/\bfrontstretch\b/gi, 'финишная прямая'],
    [/\bbackstretch\b/gi, 'задняя прямая'],
    [/\bturn (\d+)/gi, 'поворот $1'],
    [/\bnone\b/gi, '—']
  ];

  // Country / territory names for driver profiles (English key, lowercase -> ru).
  window.TGA_RU.countryNameRu = {
    'great britain': 'Великобритания',
    'britain': 'Великобритания',
    'uk': 'Великобритания',
    'united kingdom': 'Великобритания',
    'england': 'Англия',
    'scotland': 'Шотландия',
    'wales': 'Уэльс',
    'northern ireland': 'Северная Ирландия',
    'europe': 'Европа',
    'world': 'Мир',
    'italy': 'Италия',
    'monaco': 'Монако',
    'spain': 'Испания',
    'españa': 'Испания',
    'belgium': 'Бельгия',
    'france': 'Франция',
    'germany': 'Германия',
    'deutschland': 'Германия',
    'new zealand': 'Новая Зеландия',
    'australia': 'Австралия',
    'canada': 'Канада',
    'mexico': 'Мексика',
    'argentina': 'Аргентина',
    'brazil': 'Бразилия',
    'brasil': 'Бразилия',
    'netherlands': 'Нидерланды',
    'holland': 'Нидерланды',
    'the netherlands': 'Нидерланды',
    'thailand': 'Таиланд',
    'finland': 'Финляндия',
    'denmark': 'Дания',
    'norway': 'Норвегия',
    'russia': 'Россия',
    'usa': 'США',
    'united states': 'США',
    'united states of america': 'США',
    'u.s.': 'США',
    'u.s': 'США',
    'sweden': 'Швеция',
    'switzerland': 'Швейцария',
    'austria': 'Австрия',
    'poland': 'Польша',
    'czech republic': 'Чехия',
    'czechia': 'Чехия',
    'hungary': 'Венгрия',
    'portugal': 'Португалия',
    'ireland': 'Ирландия',
    'iceland': 'Исландия',
    'luxembourg': 'Люксембург',
    'andorra': 'Андорра',
    'san marino': 'Сан-Марино',
    'china': 'Китай',
    'japan': 'Япония',
    'korea': 'Корея',
    'south korea': 'Южная Корея',
    'india': 'Индия',
    'indonesia': 'Индонезия',
    'malaysia': 'Малайзия',
    'singapore': 'Сингапур',
    'philippines': 'Филиппины',
    'taiwan': 'Тайвань',
    'hong kong': 'Гонконг',
    'south africa': 'ЮАР',
    'morocco': 'Марокко',
    'algeria': 'Алжир',
    'egypt': 'Египет',
    'chile': 'Чили',
    'colombia': 'Колумбия',
    'ecuador': 'Эквадор',
    'peru': 'Перу',
    'uruguay': 'Уругвай',
    'paraguay': 'Парагвай',
    'bolivia': 'Боливия',
    'venezuela': 'Венесуэла',
    'cayman islands': 'Каймановы Острова',
    'barbados': 'Барбадос',
    'lithuania': 'Литва',
    'latvia': 'Латвия',
    'estonia': 'Эстония',
    'romania': 'Румыния',
    'bulgaria': 'Болгария',
    'slovakia': 'Словакия',
    'slovenia': 'Словения',
    'croatia': 'Хорватия',
    'serbia': 'Сербия',
    'greece': 'Греция',
    'turkey': 'Турция',
    'israel': 'Израиль',
    'uae': 'ОАЭ',
    'united arab emirates': 'ОАЭ',
    'qatar': 'Катар',
    'saudi arabia': 'Саудовская Аравия',
    'kuwait': 'Кувейт',
    'bahrain': 'Бахрейн',
    'british': 'Великобритания',
    'dutch': 'Нидерланды',
    'belgian': 'Бельгия',
    'french': 'Франция',
    'german': 'Германия',
    'italian': 'Италия',
    'spanish': 'Испания',
    'australian': 'Австралия',
    'canadian': 'Канада',
    'american': 'США',
    'japanese': 'Япония',
    'finnish': 'Финляндия',
    'danish': 'Дания',
    'swedish': 'Швеция',
    'austrian': 'Австрия',
    'swiss': 'Швейцария',
    'mexican': 'Мексика',
    'brazilian': 'Бразилия',
    'argentinian': 'Аргентина',
    'argentine': 'Аргентина',
    'thai': 'Таиланд',
    'russian': 'Россия',
    'polish': 'Польша',
    'hungarian': 'Венгрия',
    'portuguese': 'Португалия',
    'irish': 'Ирландия',
    'new zealander': 'Новая Зеландия',
    'monegasque': 'Монако',
    'colombian': 'Колумбия',
    'chilean': 'Чили',
    'south african': 'ЮАР',
    'chinese': 'Китай',
    'indian': 'Индия',
    'malaysian': 'Малайзия',
    'singaporean': 'Сингапур',
    'indonesian': 'Индонезия',
    'estonian': 'Эстония',
    'latvian': 'Латвия',
    'lithuanian': 'Литва',
    'czech': 'Чехия',
    'slovak': 'Словакия',
    'slovenian': 'Словения',
    'croatian': 'Хорватия',
    'serbian': 'Сербия',
    'greek': 'Греция',
    'turkish': 'Турция',
    'israeli': 'Израиль',
    'norwegian': 'Норвегия',
    'icelandic': 'Исландия',
    'luxembourgish': 'Люксембург',
    'andorran': 'Андорра',
    'romanian': 'Румыния',
    'bulgarian': 'Болгария',
    'venezuelan': 'Венесуэла',
    'ecuadorian': 'Эквадор',
    'peruvian': 'Перу',
    'uruguayan': 'Уругвай',
    'paraguayan': 'Парагвай',
    'bolivian': 'Боливия',
    'egyptian': 'Египет',
    'moroccan': 'Марокко',
    'algerian': 'Алжир',
    'saudi': 'Саудовская Аравия',
    'emirati': 'ОАЭ',
    'qatari': 'Катар',
    'kuwaiti': 'Кувейт',
    'bahraini': 'Бахрейн',
    'philippine': 'Филиппины',
    'filipino': 'Филиппины',
    'taiwanese': 'Тайвань',
    'hong konger': 'Гонконг',
    'korean': 'Корея',
    'south korean': 'Южная Корея'
  };

  window.TGA_RU.countryIsoRu = {
    'GB': 'Великобритания', 'IT': 'Италия', 'MC': 'Монако', 'ES': 'Испания',
    'BE': 'Бельгия', 'FR': 'Франция', 'DE': 'Германия', 'NZ': 'Новая Зеландия',
    'AU': 'Австралия', 'CA': 'Канада', 'MX': 'Мексика', 'AR': 'Аргентина',
    'BR': 'Бразилия', 'NL': 'Нидерланды', 'TH': 'Таиланд', 'FI': 'Финляндия',
    'DK': 'Дания', 'NO': 'Норвегия', 'RU': 'Россия', 'US': 'США',
    'SE': 'Швеция', 'CH': 'Швейцария', 'AT': 'Австрия', 'PL': 'Польша',
    'CZ': 'Чехия', 'HU': 'Венгрия', 'PT': 'Португалия', 'IE': 'Ирландия',
    'IS': 'Исландия', 'LU': 'Люксембург', 'AD': 'Андорра', 'SM': 'Сан-Марино',
    'CN': 'Китай', 'JP': 'Япония', 'KR': 'Южная Корея', 'IN': 'Индия',
    'ID': 'Индонезия', 'MY': 'Малайзия', 'SG': 'Сингапур', 'PH': 'Филиппины',
    'TW': 'Тайвань', 'HK': 'Гонконг', 'ZA': 'ЮАР', 'MA': 'Марокко',
    'DZ': 'Алжир', 'EG': 'Египет', 'CL': 'Чили', 'CO': 'Колумбия',
    'EC': 'Эквадор', 'PE': 'Перу', 'UY': 'Уругвай', 'PY': 'Парагвай',
    'BO': 'Боливия', 'VE': 'Венесуэла', 'KY': 'Каймановы Острова',
    'BB': 'Барбадос', 'LT': 'Литва', 'LV': 'Латвия', 'EE': 'Эстония',
    'RO': 'Румыния', 'BG': 'Болгария', 'SK': 'Словакия', 'SI': 'Словения',
    'HR': 'Хорватия', 'RS': 'Сербия', 'GR': 'Греция', 'TR': 'Турция',
    'IL': 'Израиль', 'AE': 'ОАЭ', 'QA': 'Катар', 'SA': 'Саудовская Аравия',
    'KW': 'Кувейт', 'BH': 'Бахрейн'
  };

  // Distance field + track-type phrases (event overview, specs, stats).
  window.TGA_RU.distanceParts = [
    [/(\d+(?:\.\d+)?)\s+mile\s+paved\s+track\s*\(([\d.,]+)\s+miles?\)/gi, '$1 мили, асфальтовая трасса ($2 миль)'],
    [/(\d+(?:\.\d+)?)\s+mile\s+road\s+course\s*\(([\d.,]+)\s+miles?\)/gi, '$1 мили, роуд-курс ($2 миль)'],
    [/(\d+(?:\.\d+)?)\s+mile\s+tri-oval\s*\(([\d.,]+)\s+miles?\)/gi, '$1 мили, три-овал ($2 миль)'],
    [/(\d+(?:\.\d+)?)\s+mile\s+paved\s+track/gi, '$1 мили, асфальтовая трасса'],
    [/(\d+(?:\.\d+)?)\s+mile\s+road\s+course/gi, '$1 мили, роуд-курс'],
    [/(\d+(?:\.\d+)?)\s+mile\s+tri-oval/gi, '$1 мили, три-овал'],
    [/(\d+(?:\.\d+)?)\s+miles?\s*\(([\d.,]+)\s+km\)/gi, '$1 миль ($2 км)'],
    [/(\d+(?:\.\d+)?)\s+km\s*\(([\d.,]+)\s+miles?\)/gi, '$1 км ($2 миль)'],
    [/(\d+(?:\.\d+)?)\s+km\s*\(([\d.,]+)\s+mi\)/gi, '$1 км ($2 миль)'],
    [/(\d+(?:\.\d+)?)\s+mi\s*\(([\d.,]+)\s+km\)/gi, '$1 миль ($2 км)'],
    [/(\d+(?:\.\d+)?)\s+mi\s*\/\s*([\d.,]+)\s+km/gi, '$1 миль / $2 км'],
    [/^([\d.]+)\s*\(([\d.,]+)\s+miles?\)$/i, '$1 мили ($2 миль)'],
    [/(\d+(?:\.\d+)?)\s+hours?\b/gi, '$1 ч'],
    [/paved track/gi, 'асфальтовая трасса'],
    [/road course/gi, 'роуд-курс'],
    [/street course/gi, 'уличная трасса'],
    [/permanent road course/gi, 'постоянная трасса'],
    [/street circuit/gi, 'уличная трасса'],
    [/road circuit/gi, 'шоссе'],
    [/tri-oval/gi, 'три-овал'],
    [/quad-oval/gi, 'квад-овал'],
    [/concrete oval/gi, 'бетонный овал'],
    [/paved oval/gi, 'асфальтовый овал'],
    [/dirt track/gi, 'грунтовая трасса'],
    [/half-mile/gi, 'полмили'],
    [/half mile/gi, 'полмили'],
    [/short track/gi, 'короткая трасса'],
    [/intermediate speedway/gi, 'промежуточный спидвей'],
    [/superspeedway/gi, 'суперспидвей'],
    [/all-concrete surface/gi, 'полностью бетонное покрытие'],
    [/racing surface/gi, 'гоночное покрытие'],
    [/restrictor plate/gi, 'рестрикторная панель'],
    [/restrictor size/gi, 'размер рестрикторной панели'],
    [/short oval/gi, 'короткий овал'],
    [/street circuits/gi, 'уличные трассы'],
    [/road and street circuits/gi, 'шоссе и уличные трассы'],
    [/road, street, short oval, and superspeedways/gi, 'шоссе, улицы, короткие овалы и суперспидвеи'],
    [/\bmiles\b/gi, 'миль'],
    [/\bmile\b/gi, 'мили'],
    [/\bmi\b/gi, 'миль'],
    [/\bkm\b/gi, 'км']
  ];
})();

