// Russian localization data (mapping tables, reasons, etc.)
// Logic that uses these mappings stays in app.js; this file only provides data.
(function () {
  if (typeof window === 'undefined') return;

  window.TGA_RU = window.TGA_RU || {};

  // Race statistics keys (lowercase -> ru)
  window.TGA_RU.raceStatKeysRu = {
    'cautions/laps':          'Машины безопасности / Круги',
    'cautions':               'Машины безопасности',
    'red flags':              'Красные флаги',
    'time of race':           'Время гонки',
    'average speed':          'Средняя скорость',
    'margin of victory':      'Отрыв победителя',
    'lap leaders':            'Лидеры по кругам',
    'lead changes':           'Смены лидера',
    'pole winner':            'Поулситтер',
    'pole speed':             'Скорость поула',
    'race distance':          'Дистанция гонки',
    'laps':                   'Кругов',
    'distance':               'Дистанция',
    'winners avg. speed':     'Средняя скорость победителя',
    'winning speed':          'Скорость победителя',
    'winning margin':         'Отрыв победителя',
    'total laps':             'Всего кругов',
    'laps under caution':     'Круги под SC',
    'laps led':               'Круги в лидерах',
    'cars running at finish': 'Финишировали',
    'weather':                'Погода',
    'race winner':            'Победитель',
    'fastest lap':            'Быстрейший круг',
    'fastest lap speed':      'Скорость быстрейшего круга',
    'total cars':             'Всего автомобилей',
    'dnf':                    'Сходы'
  };

  // Spec keys (lowercase -> ru)
  window.TGA_RU.specKeyRu = {
    'generation':                         'Поколение',
    'chassis':                            'Шасси',
    'model':                              'Модель',
    'body type':                          'Тип кузова',
    'body structure':                     'Конструкция кузова',
    'length':                             'Длина',
    'overall length':                     'Общая длина',
    'width':                              'Ширина',
    'overall width':                      'Общая ширина',
    'height':                             'Высота',
    'overall height':                     'Общая высота',
    'wheelbase':                          'Колёсная база',
    'minimum weight':                     'Минимальный вес',
    'minimum weight (no driver / fuel)':  'Минимальный вес (без водителя / топлива)',
    'minimum weight (with driver + fuel)':'Минимальный вес (с водителем и топливом)',
    'minimum weight (with driver)':       'Минимальный вес (с водителем)',
    'engine':                             'Двигатель',
    'engine configuration':               'Конфигурация двигателя',
    'engine displacement':                'Рабочий объём двигателя',
    'induction':                          'Впуск',
    'induction & aspiration':             'Впуск и наддув',
    'aspiration':                         'Наддув',
    'carburetor flow limit':              'Ограничение потока карбюратора',
    'power output':                       'Мощность',
    'power output restriction':           'Ограничение мощности',
    'horsepower':                         'Мощность',
    'torque':                             'Крутящий момент',
    'drivetrain':                         'Привод',
    'transmission':                       'Трансмиссия',
    'suspension':                         'Подвеска',
    'suspension (front)':                 'Передняя подвеска',
    'front suspension':                   'Передняя подвеска',
    'suspension (rear)':                  'Задняя подвеска',
    'rear suspension':                    'Задняя подвеска',
    'brakes':                             'Тормоза',
    'wheels':                             'Колёсные диски',
    'tires':                              'Шины',
    'fuel':                               'Топливо',
    'fuel type':                          'Тип топлива',
    'fuel system':                        'Топливная система',
    'fuel capacity':                      'Объём топливного бака',
    'aerodynamics':                       'Аэродинамика',
    'underbody':                          'Днище',
    'safety':                             'Безопасность',
    'safety equipment':                   'Оборудование безопасности',
    'key features':                       'Ключевые особенности',
    'vehicle type':                       'Тип транспортного средства',
    'manufacturer involvement':           'Участие производителя',
    'approved chassis builders':          'Одобренные производители шасси',
    'weight':                             'Вес',
    'displacement':                       'Объём двигателя',
    'top speed':                          'Максимальная скорость',
    'acceleration':                       'Разгон',
    'gearbox':                            'Коробка передач',
    'tire supplier':                      'Поставщик шин',
    'front wing':                         'Переднее антикрыло',
    'rear wing':                          'Заднее антикрыло',
    'monocoque':                          'Монокок'
  };

  // Table headers (lowercase -> ru)
  window.TGA_RU.tableHeaderRu = {
    'pos':                    'Поз.',
    'car':                    '#',
    'car #':                  'Ном.',
    '#':                      '#',
    'no.':                    '#',
    'no':                     '#',
    'driver':                 'Пилот',
    'official team':          'Команда',
    'team':                   'Команда',
    'manufacturer':           'Произв.',
    'best time':              'Лучш. время',
    'speed':                  'Скорость',
    'lap #':                  'Круг',
    'lap':                    'Круг',
    'laps':                   'Кругов',
    '# laps':                 'Кругов',
    'gap to leader':          'Отставание',
    'gap to next':            'До след.',
    'gap':                    'Отставание',
    'diff':                   'Разница',
    'grid':                   'Старт',
    'status':                 'Статус',
    'pts':                    'Очки',
    'points':                 'Очки',
    'bonus pts':              'Бонус',
    'laps led':               'Кр. в лидерах',
    'start pos':              'Старт. поз.',
    'starting pos':           'Старт. поз.',
    'starting position':      'Старт. поз.',
    'finishing pos':          'Фин. поз.',
    'finishing position':     'Фин. поз.',
    'flag':                   'Флаг',
    'reason':                 'Причина',
    'leader':                 'Лидер',
    'laps of caution':        'Кругов SC',
    'caution':                'SC',
    'total pts':              'Всего очков',
    'stage pts':              'Очки стейдж',
    'chassis':                'Шасси',
    'crew chief':             'Крю чиф',
    'condition':              'Состояние',
    'from lap':               'С круга',
    'to lap':                 'По круг',
    '# of laps':              'Кругов',
    'free pass':              'Своб. проезд',
    'type':                   'Тип',
    'incident':               'Инцидент',
    'cars involved':          'Авт.'
  };

  // Cell notes (exact match, lowercase)
  window.TGA_RU.cellNotesRu = {
    'disallowed after post-race inspection':      'Снят после технической проверки',
    'disallowed after post race inspection':       'Снят после технической проверки',
    'failed post-race inspection':                 'Не прошёл технический осмотр',
    'failed post race inspection':                 'Не прошёл технический осмотр',
    'disqualified':                                'Дисквалифицирован',
    'disqualified after post-race inspection':     'Дисквалифицирован после проверки',
    'did not start':                               'Не стартовал',
    'did not qualify':                             'Не прошёл квалификацию',
    'did not attempt':                             'Не принял участие',
    'withdrew':                                    'Снялся',
    'withdrawn':                                   'Снят',
    'accident':                                    'Авария',
    'engine failure':                              'Отказ двигателя',
    'transmission failure':                        'Отказ трансмиссии',
    'electrical failure':                          'Электрическая неисправность',
    'suspension failure':                          'Отказ подвески',
    'brake failure':                               'Отказ тормозов',
    'tire failure':                                'Прокол шины',
    'crash':                                       'Авария',
    'contact':                                     'Контакт',
    'overheating':                                 'Перегрев',
    'power steering failure':                      'Отказ ГУР',
    'fuel pressure':                               'Проблемы с топливом',
    'oil leak':                                    'Утечка масла',
    'lapped':                                      'На круг позади',
    'running':                                     'Финишировал',
    'dnf':                                         'Сход',
    'dns':                                         'Не стартовал',
    'dnq':                                         'DNQ',
    'wth':                                         'Снялся'
  };

  // Reason patterns
  window.TGA_RU.raceReasonParts = [
    [/\baccident frontstretch\b/gi,       'авария на финишной прямой'],
    [/\baccident backstretch\b/gi,        'авария на задней прямой'],
    [/\baccident tri-oval\b/gi,           'авария на три-овале'],
    [/\baccident turn (\d+)/gi,           'авария в повороте $1'],
    [/\baccident\b/gi,                    'авария'],
    [/\bend of stage (\d+)/gi,            'конец стейджа $1'],
    [/\bspun on backstretch\b/gi,         'разворот на задней прямой'],
    [/\bspun?\b/gi,                       'разворот'],
    [/\bdebris\b/gi,                      'посторонний предмет'],
    [/\bfluid on track\b/gi,              'жидкость на трассе'],
    [/\boil on track\b/gi,               'масло на трассе'],
    [/\bfuel on track\b/gi,              'топливо на трассе'],
    [/\bfire\b/gi,                        'пожар'],
    [/\bstalled car\b/gi,                 'заглохший автомобиль'],
    [/\bwreck\b/gi,                       'авария'],
    [/\bnone\b/gi,                        'нет']
  ];
})();

